import { ThemeRegistry } from '@/theme';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

interface LayoutProp {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProp) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
